### PR TITLE
Refactor/46 create static js edit styles

### LINKED ISSUE #46: Refactor (create JS folder in /static), edit styling a bit
Create a /js folder in /static to remove js scripts from HTML pages. Edit styling a little bit.

### PR DESCRIPTION
**Pull request by npono21**
## PR type

- [ ] Feature
- [ ] Bug Fix
- [x] Refactor
- [ ] Performance Optimization
- [ ] Documentation Update

## Description
This PR is to change the styling to dark mode as well as move any JS code out of HTML pages and into it's own dedicated /js dir in /static

## Related Issues/Tickets
closes #46 

## QA Instruction, Screenshots etc...
None

## Added/updated tests?

- [ ] Yes
- [x] No: No tests needed to html/css

## PR Checklist

- [x] I have rebased this branch against main
- [x] All the tests are passing
- [x] My commit messages are descriptive and useful

### CODE REVIEW

**Review by ArthurAtangana — CHANGES_REQUESTED** [review]
registering a merchant does not work:

```
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Tue Nov 19 00:10:08 EST 2024
There was an unexpected error (type=Method Not Allowed, status=405).
Method 'POST' is not supported.
org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' is not supported
```

**Comment by npono21** [comment]
> also, the button for registering a merchant says "submit query". please change to "register".

Should be fixed now.

**Comment by npono21** [comment]
> registering a merchant does not work:
> 
> ```
> Whitelabel Error Page
> 
> This application has no explicit mapping for /error, so you are seeing this as a fallback.
> Tue Nov 19 00:10:08 EST 2024
> There was an unexpected error (type=Method Not Allowed, status=405).
> Method 'POST' is not supported.
> org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' is not supported
> ```

Registering a merchant will not work because there is no DB set up yet. This PR is only for front-end stuff, like HTML and CSS.

**Comment by ArthurAtangana** [comment]
> > registering a merchant does not work:
> > ```
> > Whitelabel Error Page
> > 
> > This application has no explicit mapping for /error, so you are seeing this as a fallback.
> > Tue Nov 19 00:10:08 EST 2024
> > There was an unexpected error (type=Method Not Allowed, status=405).
> > Method 'POST' is not supported.
> > org.springframework.web.HttpRequestMethodNotSupportedException: Request method 'POST' is not supported
> > ```
> 
> Registering a merchant will not work because there is no DB set up yet. This PR is only for front-end stuff, like HTML and CSS.

Why not point to the controller endpoint though? as was done previously? It will handle the db stuff later but for now will resort the the h2 database as it was done in milestone 1.

**Comment by npono21** [comment]
> point to the controller endpoint though?

Okay sounds good, I have pointed it to the controller endpoint, like we current have in main.

**Pull request closed without merging**
