### PR TITLE
link frontend and backend through controller endpoints.

### PR DESCRIPTION
**Pull request by ArthurAtangana**
## PR type

- [x] Feature
- [ ] Bug Fix
- [ ] Refactor
- [ ] Performance Optimization
- [ ] Documentation Update

## Description

add annotations, endpoints to the classes and controller to navigate the frontend.
update the html to use those enpoints
mainly focused on registering a new merchant, not a login of existing
also creating a shop

## Related Issues/Tickets

closes issue #35 
## QA Instruction, Screenshots etc...

- run the jpa class
- navigate to your localhost
- register a new merchant
- create a shop.

## Added/updated tests?

- [ ] Yes
- [x] No

## PR Checklist

- [x] I have rebased this branch against main
- [x] All the tests are passing
- [x] My commit messages are descriptive and useful

### CODE REVIEW

**Review by mpdesantis — APPROVED** [review]
Awesome work connecting everything! 

I've followed your test procedures, and have no issues building, running, or using a local instance of the application. I can proceed through the Merchant registration use case we discussed for a Milestone 1 deliverable, and the only functionality missing is what you have noted in your PR description (ie. replacing the shop stubs with the newly-created shops).

Thanks Arthur!

**Comment by ArthurAtangana** [comment]
> Awesome work connecting everything!
> 
> I've followed your test procedures, and have no issues building, running, or using a local instance of the application. I can proceed through the Merchant registration use case we discussed for a Milestone 1 deliverable, and the only functionality missing is what you have noted in your PR description (ie. replacing the shop stubs with the newly-created shops).
> 
> Thanks Arthur!

just added this

**Comment by mpdesantis** [comment]
> > Awesome work connecting everything!
> > I've followed your test procedures, and have no issues building, running, or using a local instance of the application. I can proceed through the Merchant registration use case we discussed for a Milestone 1 deliverable, and the only functionality missing is what you have noted in your PR description (ie. replacing the shop stubs with the newly-created shops).
> > Thanks Arthur!
> 
> just added this

You are way too fast!!! Yes, tested and all working beautifully. I think that's our use case accomplished fully for Milestone 1.

**Review by Rebecca-Elliott — APPROVED** [review]
tested add was able to see created shop with default picture.

**Pull request merged**
